---
name: test

on: push

jobs:
  bats:
    name: bats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: make test
        run: make BATS_ARGS=--recursive test
