---
name: test

on: push

jobs:
  bats:
    name: bats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - run: docker-compose run --rm -T app test/bats/bin/bats -r test/*.bats
